# Generated by Django 4.1.7 on 2023-07-30 07:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=48)),
                ('description', models.CharField(max_length=128)),
                ('sku', models.CharField(max_length=16)),
                ('price', models.PositiveIntegerField()),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('size', models.CharField(blank=True, max_length=8, null=True)),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('material', models.CharField(max_length=32)),
                ('imageURL', models.URLField()),
                ('brandId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_generator.brand')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_generator.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_data', models.CharField(max_length=64)),
                ('qr_image', models.BinaryField()),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in', models.IntegerField(help_text='Qunatity received')),
                ('stock_out', models.IntegerField(help_text='Quantity sold or removed from stock')),
                ('stock_date', models.DateField(default=datetime.date.today, help_text='date of stock movement')),
                ('stock_type', models.CharField(help_text='e.g., Purchase, Sale, Return, etc.', max_length=32)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_generator.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleDate', models.DateField(default=datetime.date.today)),
                ('total_amount', models.IntegerField()),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_generator.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_generator.product')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_generator.sales')),
            ],
        ),
    ]
