# Generated by Django 4.1.7 on 2023-07-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_generator', '0002_brand_categorie_customer_product_qr_stock_sales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_stock',
        ),
    ]
