# Generated by Django 4.1.7 on 2023-08-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_generator', '0003_remove_product_quantity_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brandId',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categoryId',
            new_name='category',
        ),
    ]
